cart/urls.py
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(r'add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(r'remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

project/urls.py
"""
    project URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main import views

# Renaming django admin title
admin.site.site_header = 'Панель администрации'
admin.site.site_title = 'Sushiman'
admin.site.index_title = 'Модерация сайта'

urlpatterns = [
    # Django admin panel
    path('admin/', admin.site.urls),

    # Index page
    path('', views.index),

    # Cart pages
    path('cart/', include('cart.urls', namespace='cart')),
    path('adresses/', views.adresses),

    # Отображение страниц с товарами
    path(r'category/<slug:category_slug>/', views.view_category, name="main_category"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

from django.shortcuts import reverse


class Category(models.Model):
    slug = models.SlugField(
        verbose_name="Ссылка категории",
        max_length=100,
        null=False,
        blank=False,
        allow_unicode=True,
    )
    name = models.CharField(
        verbose_name="Название категории",
        max_length=100,
        null=False,
        blank=False,
    )

    image = models.ImageField(
        upload_to='static/images/caterories',
        null=True,
    )

    def __str__(self):
        return "Категория {} - {}".format(self.name, self.slug)

    class Meta:
        verbose_name = "Категория товаров"
        verbose_name_plural = "Категории товаров"


class Product(models.Model):
    image = models.ImageField(
        upload_to='media/images/products',
        null=True,
    )

    category = models.ForeignKey(
        verbose_name='Категория товара',
        to="Category",
        null=False,
        blank=False,
        on_delete=models.CASCADE,
    )

    name = models.CharField(
        verbose_name='Название',
        max_length=100,
        null=False,
        blank=False,
    )

    price = models.DecimalField(
        verbose_name='Цена',
        max_digits=6,  # До 6 цифорок
        decimal_places=2,  # Две из которых после запятой -> до 9999.99 рублей
        null=False,
        blank=False,
    )

    # TODO: Переместить в свой класс и сделать Many-To-Many или FK x2 через посредника
    compound = models.CharField(
        verbose_name='Состав',
        max_length=300,
        null=False,
        blank=False,
    )

    weight = models.IntegerField(
        verbose_name='Вес в граммах',
        null=True,
        blank=True,
    )

    def __str__(self):
        return '{} - {} / {} {} руб. {}'.format(self.id, self.category.name, self.name, self.price, self.weight)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(required=False, initial=1, widget=forms.HiddenInput)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


CITY_CHOICES =(
    ("spb", "Санкт-Петербург"),
    ("bal", "Балашиха"),
)

class OrderForm(forms.Form):
    name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={'placeholder': 'Ваше имя',
            'class':'form-control'}
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'E-mail',
            'class':'form-control'}
        )
    )

    phone = forms.CharField(
        max_length=11,
        widget=forms.TextInput(
            attrs={'placeholder': 'Номер телефона',
            'class':'form-control'}
        )
    )

    city = forms.ChoiceField(
        choices = CITY_CHOICES,

    )

    adress = forms.CharField(
        max_length= 200,
        widget=forms.TextInput(
            attrs={'placeholder': 'Адрес доставки',
            'class':'form-control'}
        )
    )

    change = forms.CharField(
        max_length=12,
        widget=forms.TextInput(
            attrs={'placeholder': 'С какой суммы нужна сдача? (если сдача не нужна, укажите "не нужно")',
            'class':'form-control'}
        )
    )

main/forms.py
from django import forms

from main.models import *

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from main.models import *

from .cart import Cart
from .forms import CITY_CHOICES, CartAddProductForm, OrderForm

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string




def base_context(request):
    context = dict()
    context['user'] = request.user
    context["site_name"] = "Sushiman"  # Строка перед | в title страницы
    context["page_name"] = "Главная"  # Строка после |
    context["page_header"] = ""  # Название страницы в display-3 стиле
    return context

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    print(form.is_valid())
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    c = base_context(request)

    c["page_name"] = "Корзина"
    c["page_header"] = "Корзина"
    c["cart"] = Cart(request)

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            data={
                'name': form.cleaned_data['name'],
                'phone': form.cleaned_data['phone'],
                'city': form.cleaned_data['city'],
                'adress': form.cleaned_data['adress'],
                'change': form.cleaned_data['change'],
                'email': form.cleaned_data['email'],
                'cart': Cart(request),
            }
            if form.cleaned_data['city'] == 'spb':
                html_body = render_to_string("mail.html", data)
                msg = EmailMultiAlternatives (subject="Новый заказ!", from_email='from_mail@gmail.com', to=['to_mail@gmail.com',])
                msg.attach_alternative(html_body, "text/html")
                msg.send()
            elif form.cleaned_data['city'] == 'bal':
                html_body = render_to_string("mail.html", data)
                msg = EmailMultiAlternatives (subject="Новый заказ!", from_email='from_mail@gmail.com', to=['to_mail@gmail.com',])
                msg.attach_alternative(html_body, "text/html")
                msg.send()
            return redirect('/')


    else:
        form = OrderForm()
    c['form'] = form
    return render(request, 'cart/detail.html', c)

main/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View

from main.models import *
from main.forms import *

from cart.forms import CartAddProductForm


def base_context(request):
    context = dict()
    context['user'] = request.user
    context["site_name"] = "Sushiman"  # Строка перед | в title страницы
    context["page_name"] = "Главная"  # Строка после |
    context["page_header"] = ""  # Название страницы в display-3 стиле
    return context

# Начальная страница
def index(request):
    c = base_context(request)
    c["page_header"] = "Меню"
    c["categories"] = Category.objects.all()
    return render(request, 'pages/index.html', c)

# Вьюха для просмотра товаров по категориям меню с фильтрацией
def view_category(request, category_slug):
    c = base_context(request)
    category = get_object_or_404(Category, slug=category_slug)
    
    c["page_name"] = category.name
    c["page_header"] = category.name
    c['products'] = Product.objects.filter(category=category)
    c['form'] = CartAddProductForm()

    return render(request, 'pages/category.html', c)

def adresses(request):
    c = base_context(request)
    c["page_header"] = "Адреса"
    c["page_name"] = "Адреса"
    return render(request, 'pages/adresses.html', c)

cart/templates/banner.html
{% load static %}

<!--Banner-->
<div class="banner-image d-flex justify-content-center align-items-center">
  <img src="{% static 'images\banner.jpg'%}" alt="" class="banner-image">
</div>
<!--Banner-->
<style>
  .banner-image {
    background-image: url("{% static 'images\banner.jpg' %}");
    width: 100%;
    height: 100%;
  }
</style>

cart/templates/base.html
{% load static %}
<!doctype html>
<html class="h-100">

<head>
	<title>{{ site_name }} | {{ page_name }}</title>

	<meta charser="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- Место под favicon !-->

	<!--Подключение шрифта-->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;500&display=swap" rel="stylesheet">

	<!--Подключение css bootstrap-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
	{% block css %}{% endblock css %}

	<!--Подключение js bootstrap-->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

	<!-- Базовые скрипты !-->
	<script src="{% static 'js/base.min.js' %}"></script>
	{% block js %}{% endblock js %}
</head>

<body class='h-100'>
	{% include 'messages.html' %}
	{% include 'header.html' %}

	{% block content %}
	{% endblock content %}


	{% include 'footer.html' %}
</body>

</html>

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block content %}
{% include 'banner.html' %}

<div class="content text-center">
  <p class="display-4 my-4">{{ page_header }}</p>
</div>
<div class="contend text-center">
  <input type="button" class="btn btn-transparent btn-lg" onclick="history.back();" value="Меню &#10229;" style="    position: relative;
  display: inline-block;
  padding: 5px 16px;
  font-size: 14px;
  font-weight: 500;
  line-height: 20px;
  white-space: nowrap;
  vertical-align: middle;
  cursor: pointer;
  -webkit-user-select: none;
  user-select: none;
  border: 1px solid;
  border-radius: 6px;
  -webkit-appearance: none;
  appearance: none;"/>
  </div>
  <br>
  <br>


<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Продукт</th>
      <th>Количество</th>
      <th></th>
      <th>Цена</th>
      <th>Общая стоимость</th>
    </tr>
  </thead>
  <tbody>
    
    {% for item in cart %}
    {% with item.product as product %}
    <tr>
      <td>
        <img src="{{ product.image.url }}" width="130px" height="100px">
      </td>
      <td>{{ product.name }}</td>
      <td>{{ item.quantity }}</td>
      <td>
        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Убрать" class="btn btn-outline-danger">
        </form>
      </td>
      <td class="num">{{ item.price }} ₽</td>
      <td class="num">{{ item.cost }} ₽</td>
    </tr>
    
    {% endwith %}
    {% endfor %}
    <tr class="total">
      <td>Сумма</td>
      <td colspan="3"></td>
      <td class="num">{{ cart.get_total_price }} ₽</td>
    </tr>
    
  </tbody>
</table>
<br>
<div class="msg msg-inform" style="display:block; border-color: #c2adf1;
background-color: #d8d1e8; 
  margin: 20px 0;
  padding: 10px 15px;
  border: 1px solid;
  border-radius: 3px; font-family: 'Oswald', sans-serif;">
  <p class="text-center">Если у вас не получается оформить заказ или вам не перезвонили в течение 5 минут, пожалуйста, свяжитесь с ближайшей к вам точкой в разделе Адреса.</p>
</div>

<form class="form-contact contact_form" action="" method="post" id="contactForm">
  {% csrf_token %}
  <div class="textbox textfield" >
    {{form.name }}
    <br>
  </div>
  <div>
    {{form.email}}
    <br>
  </div>
  <div>
    {{form.phone}}
    <br>
  </div>
  <div>
    {{form.city}}
    <br>
    <br>
  </div>
  <div>
    {{form.adress}}
    <br>
  </div>
  <div>
    {{form.change}}
    <br>
  </div>
  <div class="content text-center">
    <button type="submit" class="btn btn-outline-warning btn-lg" >Оформить заказ!</button>
  </div>
  {% csrf_token %}
</form>
{% endblock content %}

cart/templates/footer.html
{% load static %}
<footer class="blog-footer mt-4">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Наверх</a>
    </p>
    <p class="mb-1">©2021-2022 Сеть магазинов «Сушиман». Все права защищены.</p>
  </div>
</footer>

cart/templates/header.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark p-md-3">
  <div class="container">
    <a href="/" class="navbar-brand">
      <img src="{% static 'images\logo.png' %}" alt="" width="100" height="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="mx-auto">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="#" class="nav-link text-white">Адреса</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link text-white">Акции</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link text-white">Новости</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link text-white">О компании</a>
          </li>
          
        </ul>
      </div>
      
    </div>
    
  </div>
</nav>

cart/templates/mail.html
{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block content %}

<div class="content text-center">
  <p class="display-4 my-4">{{ page_header }}</p>
</div>



<table class="table table-hover">
  <thead>
    <tr>
      <th>Товар</th>
      <th>Количество</th>
      <th>Цена</th>
      <th>Общая стоимость</th>
    </tr>
  </thead>
  <tbody>
    
    {% for item in cart %}
    {% with item.product as product %}
    <tr>
      <td>{{ product.name }}</td>
      <td>{{ item.quantity }}</td>
      <td class="num">{{ item.price }} ₽</td>
      <td class="num">{{ item.cost }} ₽</td>
    </tr>
    
    {% endwith %}
    {% endfor %}
    <tr class="total">
      <td>Сумма</td>
      <td colspan="3"></td>
      <td class="num">{{ cart.get_total_price }} ₽</td>
    </tr>
    
  </tbody>
</table>


<p>Имя: {{ name }}</p>
<p>Телефон: {{ phone }}</p>
<p>Email: {{ email }}</p>
<p>Город: {{ city }}</p>
<p>Адрес доставки: {{ adress }}</p>
<p>С какой суммы нужна будет сдача: {{ change }}</p>



{% endblock content %}

cart/templates/messages.html
{% load static %}
{% if messages %}
<div aria-live="polite" aria-atomic="true" class="position-relative">
  <div class="toast-container position-absolute top-0 end-0 p-3" style="z-index:11">
    {% for message in messages %}
    <div class="toast hide align-items-center {{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="10000">
      <div class="d-flex">
        <div class="toast-body">
          {{ message }}
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

main/templates/banner.html
{% load static %}


<!--Banner-->
<div class="banner-image d-flex justify-content-center align-items-center">
  <img src="{% static 'images\banner.jpg'%}" alt="" class="banner-image">
</div>
<!--Banner-->

main/templates/base.html
{% load static %}
<!doctype html>
<html class="h-100">

<head>
	<title>{{ site_name }} | {{ page_name }}</title>

	<meta charser="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- Место под favicon !-->

	<!--Подключение шрифта-->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;500&display=swap" rel="stylesheet">

	<!--Подключение css bootstrap-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/footer.min.css' %}">
	{% block css %}{% endblock css %}

	<!--Подключение js bootstrap-->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

	<!-- Базовые скрипты !-->
	<script src="{% static 'js/base.js' %}"></script>
	{% block js %}{% endblock js %}
</head>

<body class='h-100'>
	{% include 'messages.html' %}
	{% include 'header.html' %}

	{% block content %}
	{% endblock content %}

	{% include 'footer.html' %}
</body>

</html>

main/templates/footer.html
{% load static %}

<footer class="blog-footer mt-4">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Наверх</a>
    </p>
    <p class="mb-1">©2020-2022 Сеть магазинов «Сушиман». Все права защищены.</p>
  </div>
</footer>

main/templates/header.html
{% load static %}
<nav class="navbar menu sticky-top navbar-expand-lg navbar-dark bg-dark p-md-3">
  <div class="container">
    <a href="/" class="navbar-brand">
      <img src="{% static 'images\logo.png' %}" alt="" width="100" height="40">
    </a>
    
    <div>
      <div class="mx-auto">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active" >
            <a href="adresses/" class="nav-link text-white";>Адреса</a>
          </li>
        </ul>
        
      </div>
    </div>
    
    
    <div class="cart">
      <a href="/cart/" >
      <img src="{% static 'images/cart.png' %}" width="34px" height="35px">
      </a>
    </div>
    
  </div>
  
</nav>

main/templates/messages.html
{% load static %}
{% if messages %}
<div aria-live="polite" aria-atomic="true" class="position-relative">
  <div class="toast-container position-absolute top-0 end-0 p-3" style="z-index:11">
    {% for message in messages %}
    <div class="toast hide align-items-center {{ message.tags }} border-0" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="10000">
      <div class="d-flex">
        <div class="toast-body">
          {{ message }}
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

main/templates/pages/adresses.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block content %}
{% include 'banner.html' %}

<div class="content text-center">
  <p class="display-4 my-4">{{ page_header }}</p>
</div>
<div class="contend text-center">
    <input type="button" class="btn btn-transparent btn-lg" onclick="history.back();" value="Меню &#10229;" style="    position: relative;
    display: inline-block;
    padding: 5px 16px;
    font-size: 14px;
    font-weight: 500;
    line-height: 20px;
    white-space: nowrap;
    vertical-align: middle;
    cursor: pointer;
    -webkit-user-select: none;
    user-select: none;
    border: 1px solid;
    border-radius: 6px;
    -webkit-appearance: none;
    appearance: none;"/>
    </div>
    <br>
    <br>

<div class="content text-center">
    <p style="font-family: 'Oswald', sans-serif; font-size: large;">Город Санкт-Петербург</p>
    <p style="font-family: 'Oswald', sans-serif; font-size: medium;">ул.Русановская, д.11</p>
    <p style="font-family: 'Oswald', sans-serif; font-size: medium;">с 11-00 до 23-00</p>
    <a style="font-family: 'Oswald', sans-serif; font-size: medium;" href="tel: 8 921-905-2410">8 921-905-2410</a>
    <br>
    <br>
    
    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A2b242140f1e4897b97121dfd3d6b2d900a40efdca9295c0a5ca2c238a6227b9a&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
</div>
<br>
<br>
<div class="content text-center">
    <p style="font-family: 'Oswald', sans-serif; font-size: large;">Город Балашиха</p>
    <p style="font-family: 'Oswald', sans-serif; font-size: medium;">мкр. Авиаторов, бульвар Нестерова,4</p>
    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Aa60fa9f6d7f8e2d8bb046a66de8b2b9f196a72fe3f184cc8ed39ec54a57e9f10&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
</div>
{% endblock content %}

main/templates/pages/category.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block content %}
{% include 'banner.html' %}

<div class="content text-center">
  <p class="display-4 my-4">{{ page_header }}</p>
</div>
<div class="contend text-center">
<input type="button" class="btn btn-transparent btn-lg" onclick="history.back();" value="Меню &#10229;" style="    position: relative;
    display: inline-block;
    padding: 5px 16px;
    font-size: 14px;
    font-weight: 500;
    line-height: 20px;
    white-space: nowrap;
    vertical-align: middle;
    cursor: pointer;
    -webkit-user-select: none;
    user-select: none;
    border: 1px solid;
    border-radius: 6px;
    -webkit-appearance: none;
    appearance: none;"/>
</div>
<br>
<br>
<br>

<div class="container-fluid d-flex flex-row flex-wrap justify-content-evenly">
  {% for product in products %}
  <div class="enlarge card mx-1 text-center" style="width: 300px;" data-aos="zoom-in">
    <div class="card-body">
      <img class="card-img-top" src="{{ product.image.url }}" alt="Фото {{ product.name }}" style="max-width: 500px; max-height: 500px;">
      <h5 class="card-title">{{ product.name }}</h5>
      <p class="cart-text">{{ product.compound }}</p>
      <p class="cart text-muted">{{product.weight}} гр.</p>
      <p class="card-text">{{ product.price }} ₽</p>
      
      <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ form }}
        {% csrf_token%}
        <input type="submit" class="btn btn-light" value="Добавить в корзину">
      </form>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

main/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block content %}
{% include 'banner.html' %}

<div class="content text-center">
  <p class="display-4 my-4">{{ page_header }}</p>
</div>

<div class="container-fluid d-flex flex-row flex-wrap justify-content-evenly">
  {% for category in categories %}
  <div class="enlarge card text-center" style="width: 18rem;" data-aos="zoom-in">
    <img class="card-img-top" src="{{ category.image.url }}" alt="{{ category.name }}" style="max-width: 500px; max-height: 500px; object-fit: cover;">
    <div class="card-body">
      <a class="btn btn-transparent stretched-link" href="{% url 'main_category' category.slug %}">{{ category.name }}</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}